"""`shipgate doctor` (task 3.2) — report §2.2 D6: "priority
registers rotted to 24% stale; shipfiles will rot the same way." Detects a shipfile
whose `done_conditions` reference a file, path, or pattern that no longer resolves to
anything real in the project — run at `init`, weekly, and before `evolve` per the
report's own cadence, never as part of the gate itself.

**What "stale" means here, stated precisely because the honest scope is narrower than
it sounds:** doctor does not try to distinguish "this condition is stale because the
world moved on" from "this condition is legitimately still failing, as intended." That
distinction needs human judgment doctor doesn't have. What doctor *can* do,
deterministically: for the condition types whose fields name a concrete filesystem
target, confirm the target still resolves to something on disk — the same kind of check
a link-checker runs. A dead link doesn't tell you it was *always* dead; it tells you a
human should look.

**Checked condition types, and why the other four aren't:**

- `file_exists.path` — does the path exist under the project root?
- `forbidden_pattern_absent.paths` — does each listed scope path (if any were given;
  the field is optional) exist?
- `inventory_complete.grep_pattern` — does the pattern currently match anything at all
  under the project root? Reuses `shipgate.gate.checkers.iter_scanned_files`, the exact
  scan `check_inventory_complete` itself uses — no second scanning implementation. Zero
  matches means the condition can never be satisfied as written, the same
  vacuous-signal instinct the gate's own checkers apply to test collection.
- `tests_pass` / `command_succeeds` — **not checked.** A shell command isn't a
  filesystem reference in the sense above; validating "does this command still make
  sense" would mean actually running it (that's the gate's job, on the gate's own
  timing, not a cheap hygiene scan's) or parsing shell syntax to guess at a target file,
  which risks the wrong kind of cleverness. Stated gap, not a silent omission.
- `runtime_evidence` / `emission_traced` — **not checked**, for the same reason: their
  fields (`detail`, `marker`) don't name a filesystem path at all.
- EARS-style entries (no `type` field) — **not checked**; there is no field to resolve
  against the filesystem in the first place.

**Founder review finding, fixed this session (Session 010): zero checked must never
render as "Clean."** A `shipgate init`-generated shipfile has exactly one
`done_condition` (`tests_pass`), which is not one of the three types above — so
`init` → `doctor`, the out-of-the-box path and the literal Gate C script, always
produced `"Checked 0 condition(s)."` immediately followed by `"Clean — every checked
reference still resolves."` That is `unverified-vacuous` rendered as a pass — this
project's own vacuous-pass rule applied to its own tooling rather than only to the
gate's checkers. Fixed: `DoctorReport.is_vacuous` is a distinct state from `is_clean`,
and `shipgate/cli.py`'s `doctor` command checks it first and never uses the word "clean"
for zero observations.

Zero Claude-Code-specific imports — this package is not one of the four core-purity-
restricted packages, but it has no need to know about a live Claude Code process either.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from shipgate.gate.checkers import iter_scanned_files
from shipgate.shipfile import Shipfile

#: The only condition types doctor inspects — see the module docstring for why the
#: other four are left as a stated gap rather than guessed at.
_CHECKED_TYPES = frozenset({"file_exists", "forbidden_pattern_absent", "inventory_complete"})


@dataclass(frozen=True)
class StaleReference:
    condition_id: str
    condition_type: str
    field: str
    value: str
    reason: str


@dataclass(frozen=True)
class DoctorReport:
    stale: tuple[StaleReference, ...]
    checked_condition_ids: tuple[str, ...]
    skipped_condition_types: tuple[str, ...]

    @property
    def is_vacuous(self) -> bool:
        """**Founder review finding, Session 010:** a shipfile generated by `shipgate
        init` has exactly one `done_condition` — a `tests_pass` entry — which is not one
        of the three types doctor checks. `init` then `doctor`, the out-of-the-box path
        and the Gate C script, produced `"Checked 0 condition(s)."` immediately followed
        by `"Clean"` — zero observations rendered as a pass, the same shape this
        project's own vacuous-pass rule forbids everywhere else, including its own
        tooling. `True` when nothing was actually checked, regardless of whether
        anything was skipped or why. Callers (`shipgate/cli.py`'s `doctor` command) must
        check this *before* `is_clean` and never print a clean-sounding word for this
        state."""
        return not self.checked_condition_ids

    @property
    def is_clean(self) -> bool:
        """`True` only if at least one condition was actually checked and none was
        stale. `False`, not `True`, when nothing was checked at all — see `is_vacuous`,
        which is the state that used to collapse into this property reading `True` on
        zero observations before the Session 010 fix."""
        return bool(self.checked_condition_ids) and not self.stale


def _grep_has_any_match(project_root: Path, pattern: str) -> bool:
    regex = re.compile(pattern)
    for file_path in iter_scanned_files(project_root, ["."]):
        try:
            text = file_path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        if regex.search(text):
            return True
    return False


def run_doctor(shipfile: Shipfile, project_root: Path) -> DoctorReport:
    stale: list[StaleReference] = []
    checked_ids: list[str] = []
    skipped_types: set[str] = set()

    for condition in shipfile["done_conditions"]:
        condition_type: Any = condition.get("type")
        if condition_type is None:
            # EARS-style entry — no filesystem-facing field to check.
            continue
        if condition_type not in _CHECKED_TYPES:
            skipped_types.add(condition_type)
            continue

        checked_ids.append(condition["id"])

        if condition_type == "file_exists":
            target = condition["path"]
            if not (project_root / target).exists():
                stale.append(
                    StaleReference(
                        condition_id=condition["id"],
                        condition_type=condition_type,
                        field="path",
                        value=target,
                        reason=f"{target!r} does not exist under {project_root}",
                    )
                )
        elif condition_type == "forbidden_pattern_absent":
            for scope_path in condition.get("paths", []):
                if not (project_root / scope_path).exists():
                    stale.append(
                        StaleReference(
                            condition_id=condition["id"],
                            condition_type=condition_type,
                            field="paths",
                            value=scope_path,
                            reason=f"{scope_path!r} does not exist under {project_root}",
                        )
                    )
        elif condition_type == "inventory_complete":
            pattern = condition["grep_pattern"]
            if not _grep_has_any_match(project_root, pattern):
                stale.append(
                    StaleReference(
                        condition_id=condition["id"],
                        condition_type=condition_type,
                        field="grep_pattern",
                        value=pattern,
                        reason=(
                            f"grep_pattern {pattern!r} matches zero locations under "
                            f"{project_root} — this condition can never be satisfied as written"
                        ),
                    )
                )

    return DoctorReport(
        stale=tuple(stale),
        checked_condition_ids=tuple(checked_ids),
        skipped_condition_types=tuple(sorted(skipped_types)),
    )


__all__ = ["DoctorReport", "StaleReference", "run_doctor"]
